[package]
name = "rust_api_example"
version = "0.1.0"
authors = ["Jean-Marcel Belmont <jbelmont@foodlogiq.com>"]

[dependencies]
rocket = "0.3.17"
rocket_codegen = "0.3.17"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"